#service:
#- docker

apt:
  update: true
  packages:
  - wget
  - libappindicator1
  - fonts-liberation
  - python-pip
#  - docker-ce

install: true
before_script:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb >/dev/null 2>&1
- sudo pip install httpie >/dev/null 2>&1

language: node_js
node_js: lts/*

script:
- export root=$(pwd)
- |
  for project in \
    add-css-and-styles-loaders \
    add-webpack-dev-server \
    add-html \
    starter \
    starter-no-config \
  ; do
    cd ${root}/modules/${project}
    npm i
    npm run build
  done;

#- cd $root
#- cp -Rf ./.dockerignore.frontend ./.dockerignore
#- docker build --rm --force-rm --no-cache -f Dockerfile.frontend -t daggerok/webpack-examples:frontend .
#- docker run -d --rm -p 80:80 -e "PORT=80" --name run-webpack-examples-frontend daggerok/webpack-examples:frontend
#- sleep 1
#- http http://127.0.0.1/
#- docker stop run-webpack-examples-frontend

env:
  global:
  - TERM=dumb
  # GITHUB_TOKEN:
  - secure: o41fuJ/HMTnCLvhHixG6vN6rMXvXxTiLdLiBq6x7HkAcwIoKjSFkPg5fPZiWUevDgv1caFTI7n2u4MSPbeaCT5T5uYHG1OF20T9gmsPEh2o3Y6ekIyIGkcc+BfkKV4Iz2NBrwhxsJxNbvdmokDClwrPRJZAGBDJjiY5NZkMQRa7Hk9uS8Dp34lDc1zijcBUjKfI1qb3vnpICYEhDvWz9N2cJ/jqYobrmqIsSXVZE2bfeSIZhp9DBYv/AKDiKEnO7D7HLQ26aWxLhBz2NxmyCrfCwyngxeEX4ZnQvTmDUQrC6R0oTd4kFvR7rKmrbUkk7tdBIsb7u65QqwR42yVb1dZZ++u/bju1WQiz8/Z4L61/+gPB5Uu8yA3wbcZt/L9mmXaFOrS8yvqnXCDGjhnvbKGdEyGzOIbICVuvlMIbmss2WnAGQgKd4ckyx6wfzXrmB8JXu9jLV3pbuwb03LIoJJO//88pEoI5PJvhHjiVvsBnqcVxsYpd2yMY1WiUsPkwFQkjmdPfdZYJY+vT+3T6fLlZQvzCXqvXPbkpWBsf2SakNcmpCsErbbKfGq+mmITib2x9MgepzpdUiDgFIHBzo1qj1GL054jGjvOnsCLIwBzQn2A/yN5YT13WkiUeIn+x4Wy15zWEeDkvrWBkgBEsSxXoOrY9u7m84aCZwZCIUcvk=

language: java
java: oraclejdk8

before_deploy:
- cd $root
- ./gradlew documentation

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: public
  target_branch: gh-pages
