= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
ifdef::backend-html5[image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]]

== Introduction

include::../../README.adoc[tags=content]

== Quickstart

=== no config

.using webpack without `webpack.config.js` file
[source,bash]
----
mkdir starter-no-config
cd starter-no-config/

mkdir src dist
echo "console.log('hey!');" >> src/index.js
echo "<script src='./main.js'></script>" >> dist/index.html

npm init -y
npm i -g webpack webpack-cli
#npm i -DE webpack webpack-cli

webpack --mode=development
webpack --mode production
----

=== basic config

.using webpack with basic config file: `config/webpack.dev.js`
[source,javascript]
----
include::../../modules/starter/config/webpack.dev.js[tags=content]
----

=== add HTML plugin

.install html-webpack-plugin
[source,bash]
----
npm i -DE html-webpack-plugin
----

.update webpack condig
[source,javascript]
----
include::../../modules/add-html/config/webpack.dev.js[tags=content]
----

=== add webpack-dev-server

.update webpack condig
[source,javascript]
----
include::../../modules/add-webpack-dev-server/config/webpack.dev.js[tags=content]
----

.install and run webpack-dev-server
[source,bash]
----
npm i -DE webpack-dev-server
webpack-dev-server --config config/webpack.dev.js
----

=== add css-loader and style-loader

.add some css styles
[source,css]
----
include::../../modules/add-css-and-styles-loaders/src/styles.css[]
----

NOTE: These loaders will apply in reverse order: first, `css-loader`, next: `style-loader`

.install css-loader and style-loader
[source,bash]
----
npm i -DE css-loader style-loader
----

.update webpack condig
[source,javascript]
----
include::../../modules/add-css-and-styles-loaders/config/webpack.dev.js[tags=content]
----

=== process html and using html / file loaders

.prepare `./src/index.html`
[source,html]
----
include::../../modules/using-extract-and-file-loaders/src/index.html[]
----

NOTE: Few thinks are happening here:
      First, `html-loader` will do necessary linting of *.html files.
      Then `extract-loader` will tell webpack do not include it in result bundle.js file.
      And finally `file-loader` will put extracted content in output dir accordingly

.remove useless plugin and install requires loaders: `html-loader`, `extract-loader` and `file-loader`
[source,bash]
----
npm rm -DE html-webpack-plugin
npm i -DE html-loader extract-loader file-loader
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-extract-and-file-loaders/config/webpack.dev.js[tags=content]
----

.finally combine all together in `./src/index.js`
[source,javascript]
----
include::../../modules/using-extract-and-file-loaders/src/index.js[tags=content]
----

NOTE: I wont use that approach,
      I prefer `HtmlWebpackPlugin` and `ExtractTextWebpackPlugin`

=== using extract-text-webpack-plugin

.install
[source,bash]
----
npm rm -ED style-loader
npm i -DE extract-text-webpack-plugin@next css-loader
# also add less support
npm i -DE less-loader less
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-extract-text-webpack-plugin/config/webpack.dev.js[tags=content]
----

TIP: There are better option available for using instead of extract text plugin:
     `mini-css-extract-plugin`

=== using mini-css-extract-plugin

.install
[source,bash]
----
npm rm extract-text-webpack-plugin
npm i -DE mini-css-extract-plugin
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-mini-css-extract-plugin/webpack.config.js[tags=content]
----

.update package.json
[source,json]
----
{
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack",
    "build": "cross-env NODE_ENV=production webpack",
    "start": "cross-env NODE_ENV=development webpack-dev-server --open"
  }
}
----

=== using optimize-css-assets-webpack-plugin

NOTE: THis plugin solves extract-text-webpack-plugin CSS duplication problem

.install
[source,bash]
----
npm i -DE optimize-css-assets-webpack-plugin
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-optimize-css-assets-webpack-plugin/webpack.config.js[tags=content]
----

=== using webpack config as a function

.remove useless packages
[source,bash]
----
npm rm cross-env
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-webpack-config-as-a-function/webpack.config.js[tags=content]
----

== Links

ifdef::backend-html5[- link:./index.pdf[Documentation in PFD format]]
- link:https://asciidoctor.org/docs/user-manual/#source-code-blocks[Asciidoctor reference]
- link:https://github.com/lawwantsin/webpack-course[GitHub repo: lawwantsin/webpack-course]
- link:https://github.com/daggerok/{root-project-name}[GitHub]
- link:https://webpack.js.org/concepts/[Webpack documentation]
- link:https://webpack.js.org/plugins/html-webpack-plugin/[HTML webpack plugin documentation]
- link:https://webpack.js.org/configuration/dev-server/#src/components/Sidebar/Sidebar.jsx[HTML webpack-dev-server documentation]
- link:https://github.com/peerigon/extract-loader[extract-loader]
- link:https://webpack.js.org/plugins/extract-text-webpack-plugin/#src/components/Sidebar/Sidebar.jsx[extract-text-webpack-plugin]
- link:https://github.com/NMFR/optimize-css-assets-webpack-plugin[optimize-css-assets-webpack-plugin]
