= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
ifdef::backend-html5[image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]]

== Introduction

include::../../README.adoc[tags=content]

== Quickstart

=== no config

.using webpack without `webpack.config.js` file
[source,bash]
----
mkdir starter-no-config
cd starter-no-config/

mkdir src dist
echo "console.log('hey!');" >> src/index.js
echo "<script src='./main.js'></script>" >> dist/index.html

npm init -y
npm i -g webpack webpack-cli
#npm i -DE webpack webpack-cli

webpack --mode=development
webpack --mode production
----

=== basic config

.using webpack with basic config file: `config/webpack.dev.js`
[source,javascript]
----
include::../../modules/starter/config/webpack.dev.js[tags=content]
----

=== add HTML plugin

.install html-webpack-plugin
[source,javascript]
----
npm i -DE html-webpack-plugin
----

.update webpack condig
[source,javascript]
----
include::../../modules/add-html/config/webpack.dev.js[tags=content]
----

=== add webpack-dev-server

.update webpack condig
[source,javascript]
----
include::../../modules/add-webpack-dev-server/config/webpack.dev.js[tags=content]
----

.install and run webpack-dev-server
[source,javascript]
----
npm i -DE webpack-dev-server
webpack-dev-server --config config/webpack.dev.js
----

=== add css-loader and style-loader

.add some css styles
[source,css]
----
include::../../modules/add-css-and-styles-loaders/src/styles.css[]
----

NOTE: These loaders will apply in reverse order: first, `css-loader`, next: `style-loader`

.install css-loader and style-loader
[source,javascript]
----
npm i -DE css-loader style-loader
----

.update webpack condig
[source,javascript]
----
include::../../modules/add-css-and-styles-loaders/config/webpack.dev.js[tags=content]
----

=== process html and using html / file loaders

.prepare `./src/index.html`
[source,html]
----
include::../../modules/using-extract-and-file-loaders/src/index.html[]
----

NOTE: Few thinks are happening here:
      First, `html-loader` will do necessary linting of *.html files.
      Then `extract-loader` will tell webpack do not include it in result bundle.js file.
      And finally `file-loader` will put extracted content in output dir accordingly

.remove useless plugin and install requires loaders: `html-loader`, `extract-loader` and `file-loader`
[source,javascript]
----
npm rm -DE html-webpack-plugin
npm i -DE html-loader extract-loader file-loader
----

.update webpack condig
[source,javascript]
----
include::../../modules/using-extract-and-file-loaders/config/webpack.dev.js[tags=content]
----

.finally combine all together in `./src/index.js`
[source,javascript]
----
include::../../modules/using-extract-and-file-loaders/src/index.js[tags=content]
----

== Links

ifdef::backend-html5[link:./index.pdf[Documentation in PFD format]]

link:https://asciidoctor.org/docs/user-manual/#source-code-blocks[Asciidoctor reference]

link:https://github.com/lawwantsin/webpack-course[GitHub repo: lawwantsin/webpack-course]

link:https://github.com/daggerok/{root-project-name}[GitHub]

link:[Webpack documentation]

link:https://webpack.js.org/plugins/html-webpack-plugin/[HTML webpack plugin documentation]

link:https://webpack.js.org/configuration/dev-server/#src/components/Sidebar/Sidebar.jsx[HTML webpack-dev-server documentation]

link:https://github.com/peerigon/extract-loader[extract-loader]
